### ISSUE TITLE
針對大易輸入法使用者說明

### ISSUE THREAD

**Issue by takeda0361** [plateaukao/sweetlime#10]
首先謝謝作者fork這麼好用的輸入法
在原版LIME下架後還能繼續維護更新
相當感動

Sweet LIME版本只有內建注音
經測試大易可以相容
需要一些步驟

1.自備大易字根cin檔->匯入
2.匯入後到左上角->大易->將鍵盤由LIME預設->切換為大易字根鍵盤
3.右上角設定->拉到最下->勾選啟動數字對應

以上調整完成就能自在使用大易輸入法

但我用v6.7.1版本
打字震動好像無效?
不曉得其它人是否一樣

**Comment by plateaukao** [comment]
你進設定，把震動調到最強看看
