### ISSUE TITLE
使用OOS12安裝出現剖析套件出現問題。

### ISSUE THREAD

**Issue by HsiehYifang** [plateaukao/sweetlime#11]
你好
我使用一加手機oos android12系統，6.6.0版本安裝沒有問題，但6.7.0，6.7.1的版本無法安裝，安裝時會出現"剖析套件時出現問題"。
試著使用其它手機下載及安裝沒問題。用PC將安裝檔傳送到一加手機時，依然是一樣的情形。
應該是手機oos12系統的問題。
或是有看到這個例子：https://medium.com/@lewwybogus/fixing-there-was-a-problem-while-parsing-the-package-on-android-12-d62365d5a8b

**Comment by plateaukao** [comment]
好的，我改一下試試

**Comment by plateaukao** [comment]
@HsiehYifang  請再試一下 6.7.2 應該是解了 :)

**Comment by HsiehYifang** [comment]
謝謝。
問題已經解決了。

Daniel Kao ***@***.***> 於 2022年7月4日 週一 21:24 寫道：
