### ISSUE TITLE
Firefox蒐尋列打字第一個字會出現字碼而不是中文字

### ISSUE THREAD

**Issue by subdrifter** [plateaukao/sweetlime#12]
非常謝謝你維護了這個版本的lime。

不確定是不是firefox的問題，但在它蒐尋列直接打字時，選定中文字會輸入該字的嘸蝦米字碼，而不是那個字本身。

**Comment by plateaukao** [comment]
我裝了 Firefox 來試，會正常顯示中文喔。請問你使用的手機型號和 Android 版本是多少呢？如果我有類似的手機，我可以來試試

**Comment by subdrifter** [comment]
hi Daniel,

環境是Asus 5Z，原廠Android 10．剛剛再試了一下，不是每一個字都會這樣:
出字: 們(qm)，微(rz)
出字碼: 我(ix)，自(pm)

供你參考，謝謝！那又或許是參考檔的問題？但其它的app並沒有這個狀況．

另外也常常遇到鍵盤有鍵持續被點亮的狀況(僅限空白鍵、123)。使用上沒有問題。

**Comment by kiki8866** [comment]
我用firefox,也有類似情況,samsung s21fe,原廠android12.
不過,無論按那一個只有一個的侯選字,都是會出英文字.並不是其他輸入法字根.
ml-安
lo-如

**Comment by subdrifter** [comment]
上網找了一下，能找到最後一個版本的apk，版號是5.2.4。用起來沒有這樣的問題。

但GitHud看似最新的原始碼只到5.0.7，要重新維護，可能是有少掉中間一段的修正。我也試了一下5.0.7的apk檔，有一樣的問題。

**Comment by kiki8866** [comment]
今天升上android13後,firefox好像也有更新,不知是那邊,總之現在沒這個問題了.
