### ISSUE TITLE
注音候選字消失

### ISSUE THREAD

**Issue by wanderoo8646** [plateaukao/sweetlime#13]
例如「裔」，用注音輸入法輸入 一ˋ 出現的候選字只有 10 個字，找不到「裔」，而原本的 limehd 全部都可以正常出現
![Screenshot_2022-07-05-18-08-50-404_com mycompany app soulbrowser](https://user-images.githubusercontent.com/75575982/177305325-dceb12e4-c25b-4124-bc4b-7c5d2ebeadc5.jpg)

**Comment by plateaukao** [comment]
可能是因為我把搜尋的字改為最多只顯示5個候選字了吧(因為我都是用自建字庫的無蝦米，重碼字不會那麼多)。我再看能不能改成只有自建字庫才只顯示 5 個候選字。

**Comment by wanderoo8646** [comment]
我也是用自建字庫的大易，難怪有時候覺得顯示的候選詞有少
