### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by aricksun** [plateaukao/sweetlime#15]
請問速成輸入法要去那裡下載
謝謝您

**Comment by plateaukao** [comment]
您好，我不清楚喔。我主要是在使用嘸蝦米。

**Comment by aricksun** [comment]
原始的版本，有內建下載點，目前看到的只有注音。

**Comment by plateaukao** [comment]
可能是我後來修改時，有把它們都移除了。如果你想要下載原始的版本，可以到 https://github.com/lime-ime/limeime/releases/tag/5.0.6-517 看看。 :)

**Comment by aricksun** [comment]
好的
謝謝您

Daniel Kao ***@***.***> 於 2022年7月19日 週二 21:29 寫道：

**Comment by aricksun** [comment]
不好意思請問在那可以取得
.cin
.lime
字根檔案
做匯入使用
謝謝您

文清 ***@***.***> 於 2022年7月20日 週三 19:45 寫道：

**Comment by plateaukao** [comment]
@aricksun  這邊可能有 https://github.com/openvanilla/openvanilla/tree/master/DataTables
