### ISSUE TITLE
使用自建輸出入法時，可以讓建盤顯示為還大寫嗎？

### ISSUE THREAD

**Issue by devenhala** [plateaukao/sweetlime#20]
使用自建輸出入法時，可以讓建盤顯示預設為還大寫嗎？
類似像無蝦米官方版的樣式。

**Comment by plateaukao** [comment]
目前不會考慮做這樣的修改喔。
萊姆輸入法在輸入中文時，可以直接輸入英文，也可以用shift 鍵切換大小寫。如果預設就讓顯示的英文字母是大寫的話，這樣子在中文模式下要混著輸入英文時，就會很不清楚，究竟現在輸入的英文會是大寫還是小寫。

**Comment by devenhala** [comment]
另外請教，在左下的那個按鍵是可以不顯示的嗎？我想讓空白鍵長一些，比較不容易按錯。

![image](https://user-images.githubusercontent.com/23516205/210048683-6b56c15a-7de3-4652-8ce5-4da19d39d168.png)

**Comment by plateaukao** [comment]
因為我會使用那個鍵，所以不會特地把它移除或改成可移除喔。
