### ISSUE TITLE
加上colemak layout keyboard

### ISSUE THREAD

**Issue by hsieh123** [plateaukao/sweetlime#24]
您好，我是無蝦米使用者，最近想花點時間將qwerty layout替換成colemak layout, 幾年前有過開發android apk的經驗，但沒有開發input method的經驗，能請你指點一下哪些是關鍵的檔案我應該修改的嗎？

**Comment by plateaukao** [comment]
當你利用匯入字根表，新增輸入法後，在萊姆輸入法 app 的畫面，可以點左上角的 三，點選你的無蝦米輸入法；它會跳出新的畫面讓你可以選擇你要的鍵盤型式。如果上面你有成功加入新鍵盤 layout 的話，就可以利用這方式去切換成 colemak layout。

**Comment by hsieh123** [comment]
謝謝你，我找了一個下午，為了將新鍵盤layout加到你說的鍵盤型式選單(應是fragment_dialog_keyboard)，但始終找不到怎麼加入自定義的lime_colemak.xml到db的keyboard table裡，所以在`getKeyboardObj()`的時候cursor會找不到我自己定義的keyboard 而出錯(因為根本沒加入)。 我最後放棄(還有更重要的事等著我做)，用最下流的方法:把lime.xml內容直接替換成lime_colemak.xml！還是謝謝你的建議啊！

**Comment by plateaukao** [comment]
原來是在 db 啊~ 那可能要用 tool 去修改一下 db :D
之後我有時間的話，再把你這個鍵盤 layout 也放進去囉，感謝~
