### ISSUE TITLE
Android 13 still cannot use text-to-speech, which is supposed has been fixed in version 6.8

### ISSUE THREAD

**Issue by Kingmanyi** [plateaukao/sweetlime#27]
My phone is Vivo Iqoo 8 pro, once I upgrade to Android 13, cannot use the text-to-speech in HDLime. Even download sweetlime 6.8 and even 6.9. The text-to-speech is working perfectly in google app now.

Any idea? Thanks in advanced.

**Comment by Kingmanyi** [comment]
要先解除原有的hdlime

**Comment by wesley7790** [comment]
已試過先移除舊版，在安裝一樣出現 "應用程式套件與現有套件衝突，因此未能完成安裝"，已經先裝回舊版了。謝謝。

**Comment by plateaukao** [comment]
@Kingmanyi 
請問你手機上有裝 Google 的語音輸入嗎？有安裝的話應該要可以才對

@wesley7790 
請問有寫出來是跟什麼套件衝突嗎？
理論上如果移除掉舊版後，不會出現這樣的錯誤才對。

**Comment by wesley7790** [comment]
經網路搜尋
Installation failed! Error code: 5
INSTALL_FAILED_UPDATE_INCOMPATIBLE: Existing package net.toload.main.hd signatures do not match newer version; ignoring! 
-------------------------------
stackoverflow解決方法:
https://stackoverflow.com/questions/41709102/package-signatures-do-not-match-the-previously-installed-version

將原舊有程式->為所有人移除程式 後安裝limehd 6.9.0版已可正常使用，google語音也可使用了 感謝。

**Comment by Kingmanyi** [comment]
> 已試過先移除舊版，在安裝一樣出現 "應用程式套件與現有套件衝突，因此未能完成安裝"，已經先裝回舊版了。謝謝。

移除舊版後, 要先重啟一次, 再安裝sweetlime

**Comment by Kingmanyi** [comment]
> @Kingmanyi 請問你手機上有裝 Google 的語音輸入嗎？有安裝的話應該要可以才對
> 
@

是那個語音輸入? 我的google search, google map, chrome 都可語音輸入

**Comment by Kingmanyi** [comment]
終於成功了, 原來要安裝speech services by google 才可以, 可能我的iqoo 10 pro 原本沒有吧, 再次謝謝Daniel 師兄的幫助!
