### ISSUE TITLE
新增輸入法，可以多加大易嗎？

### ISSUE THREAD

**Issue by liu168tw** [plateaukao/sweetlime#29]
你好，原舊版本新增輸入法有多種可選，自訂的給嘸蝦米用，新版本的新增輸入法只剩注音而已，能否幫忙多加一個『大易』嗎？感謝你的幫忙。

**Comment by Kingmanyi** [comment]
可試試在原舊版本export 佢輸入法, 再在sweetlime import

**Comment by Kahgus** [comment]
> 可試試在原舊版本export 這輸入法, 再在sweetlime import

這方法我嘗試了，不行

**Comment by liu168tw** [comment]
那應該只剩把原本的新增輸入法的大易加回，才能使用大易了，按鍵上才會有相對應的鍵盤字根。

**Comment by plateaukao** [comment]
@liu168tw 如果只是要呈現鍵盤對應的字根，可以在匯入後，點選左上角，然後選擇剛匯入的輸入法，再點畫面上方的鍵盤按鈕，就可以換成其他想要的鍵盤字母呈現方式。

@Kahgus 
可以用這方式去 Google 上找大易的字根檔，附檔名是 .cin
https://www.google.com/search?q=%E5%A4%A7%E6%98%93+cin&oq=%E5%A4%A7%E6%98%93+cin&sourceid=chrome&ie=UTF-8

應該是可以匯入成自建輸入法的。

= = = = =
在我目前的版本要加回大易，會比當初刪除一大堆對應的程式碼還要麻煩很多，所以我應該不會去做這件事 (除非哪天我也想學大易了 :D)

如果上述的方法還是不行的話，你也可以考慮在它原本的 github repository 中，下載它很久以前的版本；或是從 apkpure 之類的網站上，找很久以前它下架前的版本來用。

**Comment by springminhcm** [comment]
你好，其實我也是大易的使用者(四十多快五十歲了)......今天換手機時才知道萊姆輸入法不能用在新手機上了
一整個晴天霹靂 ......
後來我下載了你的版本，匯入字根後.......目前發覺數字鍵0-9與「,./」三個鍵無法帶出字根.......
由於大易的0-9與「,./」是屬於它的字根表，目前程式使用者會直接帶出數字......
所以等於大易是無法使用的......請問好心的版主有辦法修正一下程式嗎？
目前變成只能使用手寫了......@@

**Comment by springminhcm** [comment]
@plateaukao 哇!!!!非常感謝，原來還有這個設定(因為以前萊姆輸入法使用大易時這個設定好像是作者預設就這樣)，我設好後就能用了，非常、非常的感謝你的提醒~~~!!謝謝您。

話說.....昨天我看著我的新手機，想像著我以後只能像老人家一樣用手寫輸入法時......那時真的覺得自己老了@@.........

**Comment by plateaukao** [comment]
大易的字根是公開的，所以有很多輸入法app有支援，總是能找到合用的。無蝦米比較可憐。XD

**Comment by slingshot4fun** [comment]
> @springminhcm 在萊姆輸入法的設定中，有"啟動數字對應"，和"啟動符號對應"，兩個選項，你可以都開啟看看。

請問有試過行列輸入法嗎？目前鍵盤樣式ok，但是按鍵出的是英文，而不是字根的值。

**Comment by SmithCCho** [comment]
> > @springminhcm 在萊姆輸入法的設定中，有"啟動數字對應"，和"啟動符號對應"，兩個選項，你可以都開啟看看。
> 
> 請問有試過行列輸入法嗎？目前鍵盤樣式ok，但是按鍵出的是英文，而不是字根的值。

行列30在sweetlime可正常使用，沒問題的。 
只不過不支援一二級簡碼打法，原生lime就沒有了，不過lime的字根及字詞預測比打簡碼快。
