### ISSUE TITLE
LIME HD 升級Android  13 

### ISSUE THREAD

**Issue by rmmaniac** [plateaukao/sweetlime#33]
大大
我也是升級Android13的苦主，lime hd麥克風不能用，
看到這裡有解，很高興下載安裝，但是沒有行列輸入法😭，
懇請大大是否可以Release有其他輸入法選項的版本，造福鄉民，感恩~~

p.s(版本6.1,0還有行列輸入法，是否可更改支援google語音麥克風)

**Comment by j796160836** [comment]
目前看到原始 Source code 只到 5.0.6 
不確定您說的哪個版本行列輸入法
小弟雖不是行列輸入法的使用者，或許可以幫忙把它加進去專案裡

https://github.com/lime-ime/limeime

**Comment by plateaukao** [comment]
1. 我在 android 15 上，還是從 sweetlime 中使用 google 語音麥克風。所以你可以看一下是不是哪裡設定錯了。
2. 無，希望有其他大大可以 fork 一版去幫忙加入有其他輸入法的版本。

**Comment by wanderoo8646** [comment]
Realme GT6 Android 14 按 Sweet LimeHD 麥克風無法使用語音輸入

我的解決方法：在 soul browser app 搜尋欄按麥克風，這時候輸入法的麥克風就復活了

6.1.0 是網路上某人針對 Android 13 無法使用麥克風自行修改的版本，似乎就是對應你的 6.0.9 版本號碼


[6.1.0](https://bingfong.com/forum.php?mod=viewthread&tid=1913361&extra=page%3D1&ordertype=2&threads=thread)
