### ISSUE TITLE
中文輸入可以支援多種嗎？

### ISSUE THREAD

**Issue by SmithCCho** [plateaukao/sweetlime#38]
作者 您好

因為我本身會打嘸蝦米以及行列，若使用sweetlime只能擇其一輸入法來匯入字根設定。
想請問sweetlime有機會可以支援多種中文輸入切換嗎？

感謝您

**Comment by plateaukao** [comment]
@SmithCCho 
應該沒有機會喔。我只是稍微改一改來自用的。 :)

**Comment by SmithCCho** [comment]
感謝～只能單用一種就很好用了。
我是嘸蝦米跟行列雙棲，手持行動裝置目前我幾乎都用行列10～
