### ISSUE TITLE
可否新增這些功能

### ISSUE THREAD

**Issue by lanesaga** [plateaukao/sweetlime#4]
您好
自由大新部份拆碼會使用到 ; (分號)鍵
萊姆找好久都沒找到開啟的方法
意外找到您的這個改版
第一, 希望能有個選項可以開啟新增分號鍵的功能

第二,  倉頡是以26個英文為基礎輸入 (好像無蝦也是)
少部份字拆碼才會用到上方的數字鍵 (1-0那一排) 選字
在android中, 遇到覆數字並不需要按數字鍵選字
因此, 能否增加選項, 關掉1-0讓可視畫面變大 (不是指虛擬鍵盤)

第三, 原本萊姆有其他顏色鍵盤能選, 現在變成全白
現在不少手機都是用OLED螢幕, 用深黑色模式會比較省電
是否能增加黑色鍵盤, 用起來比較不奇怪

第四, 123切換數字鍵盤, 能否改為九宮格模式
輸入一些驗證碼較為方便

**Comment by plateaukao** [comment]
@lanesaga 
1. 長按  .  就會出現分號喔
2. 這要研究看看
3. 在喜好設定中，有鍵盤樣式可以選擇。你可以選擇深色模式
4. 目前研究，有機會做得到。但目前一旦切過去就無法切回原本模式了。我要再研究看看

**Comment by lanesaga** [comment]
您好, 長按 . 會出現分號我是知道的,  我並不是只要輸入分號
而是拆碼上需要使用到, 自由大新遇到選碼字會用到分號
鍵盤的ASDF這排最右邊還是有空間能再放一鍵, 如果可以的話, 希望能新增

深色模式有找到了, 謝謝你.
