### ISSUE TITLE
候選字被遮蔽

### ISSUE THREAD

**Issue by wanderoo8646** [plateaukao/sweetlime#40]
更新至 7.0.1 候選字會被新增功能（貼上）所顯示的方塊遮蔽
![Screenshot_2024-10-30-13-26-24-06_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/user-attachments/assets/adf7f562-673d-4c9b-ad8b-683f53a3de43)

**Comment by plateaukao** [comment]
會再試著修正一下，謝謝回報

**Comment by SmithCCho** [comment]
電話數字鍵盤也是如此
另外想問，我原先是6.9版本，下載7.0.1更新後APP不是覆蓋舊版而是產生另一個新APP？

謝謝～

![IMG_4263](https://github.com/user-attachments/assets/9e340db7-70b4-4917-b361-94abdaaef0ec)
![IMG_4264](https://github.com/user-attachments/assets/a0349739-ce6f-4c08-81e4-531edcc7e643)
![IMG_4265](https://github.com/user-attachments/assets/6b956b33-32da-44e1-a6c7-105a2f74a604)

**Comment by plateaukao** [comment]
對，有換 app 名稱。 不過 7.0 只多了個 貼上 的按鈕，不見得需要升級。 您提的譏問題在 7.0.2 修復了。

**Comment by wanderoo8646** [comment]
更新至 7.0.2 貼上的按鈕不見了？
![Screenshot_2024-11-02-14-48-52-53_2c2851f616de21a6da6fb44c83a25e93](https://github.com/user-attachments/assets/7594e77b-4f4b-40e5-a171-5aba92ec42d2)

**Comment by plateaukao** [comment]
改成長按 麥克風 按鈕就可以貼上。 (因為我搞不定新增一個按鈕會有白色色塊的問題

**Comment by wanderoo8646** [comment]
成功解決問題
