### ISSUE TITLE
小小建議

### ISSUE THREAD

**Issue by SaqibuKisasa** [plateaukao/sweetlime#5]
謝謝你的分享
希望鍵盤介面可以多一種選擇
我是使用無蝦米輸入法
非常頻繁使用空白鍵
但原始的介面空白鍵長度過短
希望能把空白鍵改長一點，或讓介面更方便打字
謝謝，打擾了

**Comment by plateaukao** [comment]
@SaqibuKisasa 
好喔。我會研究看看怎麼修改。
請問你用的設備是？

**Comment by SaqibuKisasa** [comment]
我的手機是三星的a52s，謝謝你

**Comment by SaqibuKisasa** [comment]
謝謝你，我使用的是三星a52s

取得 Android 版 Outlook<https://aka.ms/AAb9ysg>
________________________________
