### ISSUE TITLE
關於更舊的設備

### ISSUE THREAD

**Issue by TxJxCh** [plateaukao/sweetlime#8]
我知道這個問題有點蠢，
但是我有一台Android4.4的設備，偷偷的改了target sdk之後安裝成功了但打不開
想問一下有機會推出Android4.4可用的版本嗎？

**Comment by plateaukao** [comment]
@TxJxCh 
你好，之前有試著支援。但花了幾天的時間，一直搞不定，要修改的內容太多了。Android 4.4 已經是十幾年前的版本，很多新的系統功能都不支援，如果硬要將 EinkBro 改到可以在 Android 4.4 上能執行，日後在維護上，可能會比開發新功能還花時間。因為我自己沒這需求，就看有沒有也懂程式又剛好有需要的人，自己 fork 一版去改了。
