### ISSUE TITLE
顯示剛打的字在鍵盤中間，文字顏色應該要根據鍵盤主題呈現對比

### ISSUE THREAD

**Issue by rwu823** [plateaukao/sweetlime#9]
首先感謝大大無私分享 lime 修改版:heart:。希望可以有方式 donate 支持 XD

這功能很實用但有一點色系的問題:
目前 `顯示剛打的字在鍵盤中間` 文字為黑色，搭配在鍵盤主題是白色的沒有問題，但如果是黑色鍵盤主題會看不清楚。:pray:

**Comment by plateaukao** [comment]
@rwu823  沒有方式可以 donate XD 大家用得開心就好。
我的手機也是套用黑色主題，但畫面中間的字是白的。(可能我 local 有改過了，我再看一下 :))

**Comment by rwu823** [comment]
@plateaukao `v6.7.0` 一樣有問題，我是 android 11 QQ

**Comment by plateaukao** [comment]
我試出來了。我再修修看

**Comment by plateaukao** [comment]
@rwu823  please try again: https://github.com/plateaukao/sweetlime/releases/tag/v6.7.1

**Comment by rwu823** [comment]
@plateaukao `v6.7.1` is working great, thanks.

**Comment by rwu823** [comment]
@plateaukao v6.7.1 is working great, thanks.
